* ezmonic-mobile

Must use modified version of CLI that gives ability to pass a "flavor" flag.

Android builds have a concept of "flavor" that I'm taking advantage of to have free/pro versions. The React CLI doesn't (didn't?) have a way to pass those in. So look to https://github.com/eihli/cli for the fork.

** How to set up the app?

*** CLI

- `shadow-cljs server`
- `shadow-cljs watch :app`
- `npx react-native start`
- `npx react-native run-android --flavor [pro/free]`
- Connect to repl <SPC m C>

*** The default way

In the top level of the repo run

: npm install

to install shadow.cljs and its dependencies.

Then to install the dependencies of the mobile app


: cd react-native && npm install

For Emacs:

: M-x cider-jack-in-cljs

and when prompted for the REPL type, enter *shadow* and when prompted
for the app type enter *:app*.

Any other editor:

: shadow-cljs watch app

** Start Metro

Then to load the app and start Metro (it'll start it in a separate tab
of your terminal):


: react-native run-android

(Note: you'll need to start Android emulator first.)

or

: react-native run-ios

** Production build

: shadow-cljs release app
